// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANwJS1zJ2pNA5fjMuXaHOTlwrqsNwPuwM',
    appId: '1:919396849914:android:1eb2e399587062fffc9143',
    messagingSenderId: '919396849914',
    projectId: 'survival-optimiser',
    storageBucket: 'survival-optimiser.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9TE3cXGdXBYdWPlhIyjg9-3vWm9f_RSU',
    appId: '1:919396849914:ios:6929a32233abb9c6fc9143',
    messagingSenderId: '919396849914',
    projectId: 'survival-optimiser',
    storageBucket: 'survival-optimiser.firebasestorage.app',
    iosBundleId: 'com.silverfern.survivaloptimizer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjWLkjn5N_Yzm9zBR30gCKeK5zPBZBnLw',
    appId: '1:919396849914:web:9533cc17bd6dad0ffc9143',
    messagingSenderId: '919396849914',
    projectId: 'survival-optimiser',
    authDomain: 'survival-optimiser.firebaseapp.com',
    storageBucket: 'survival-optimiser.firebasestorage.app',
    measurementId: 'G-KK65W8BHZD',
  );

}