name: app
description: Survival Optimizer entry point
publish_to: none
resolution: workspace
version: 1.0.0+1

environment:
  sdk: "^3.11.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  presentation:
    path: ../packages/presentation
  application:
    path: ../packages/application
  data:
    path: ../packages/data
  domain:
    path: ../packages/domain
  design_system:
    path: ../packages/design_system
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
